#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh
wmname LG3D

bspc monitor DisplayPort-0 -d I II III IV V VI VII VIII
bspc monitor eDP -d IX X

# Order monitors according to where I want workspaces to be
bspc wm -O DisplayPort-0 eDP

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

# Find classnames for each application by using xprop and clicking on the application's window
# Look for second string in WM_CLASS
# My rules
bspc rule -a Standard\ Notes -o desktop='^9' focus=off follow=off 
bspc rule -a firefox -o desktop='^1' focus=off follow=off split_dir=north
bspc rule -a Alacritty -o desktop='^1' focus=off split_dir=south
bspc rule -a xfreerdp desktop='^4' focus=off state=fullscreen
bspc rule -a 'VirtualBox Machine' desktop='^4' focus=off state=fullscreen
bspc rule -a Steam monitor=DisplayPort-0 state=fullscreen

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'

# autostart some apps 
standardnotes-desktop &
firefox &
alacritty -e tmux &
