#! /bin/zsh

sxhkd &
wmname LG3D &
if [[ "$(hostname)" == "petalchaser" ]]; then
    $HOME/.config/polybar/launch.sh
else
    $HOME/.config/polybar/toggle.sh &
fi

if [[ "$(hostname)" == "petalchaser" ]]; then
    bspc monitor DisplayPort-0 -d I II III IV V VI VII VIII
    bspc monitor eDP -d IX X XI XII
    
    # Order monitors according to where I want workspaces to be
    bspc wm -O DisplayPort-0 eDP
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

if [[ "$(hostname)" == "petalchaser" ]]; then
    bspc config normal_border_color "#44475a"
    bspc config active_border_color "#6272a4"
    bspc config focused_border_color "#ff79c6"
    bspc config presel_feedback_color "#6272a4"
fi

#Common
bspc rule -a firefox -o desktop='^1' focus=off follow=off split_dir=north split_ratio=0.6
bspc rule -a Alacritty -o desktop='^1' focus=off split_dir=south split_ratio=0.4
bspc rule -a vlc desktop='^2' focus=off 
bspc rule -a Skype desktop='^2' focus=off 
bspc rule -a VirtualBox\ Manager desktop='^3' focus=off 
bspc rule -a VirtualBox\ Machine desktop='^2' focus=off 
# Find classnames for each application by using xprop and clicking on the application's window
# Look for second string in WM_CLASS
# My rules
if [[ "$(hostname)" == "petalchaser" ]]; then
    bspc rule -a Standard\ Notes -o desktop='^9' focus=off follow=off 
    bspc rule -a Steam monitor=DisplayPort-0 state=fullscreen
fi

# External rule for android emulator
bspc config external_rules_command ~/.config/bspwm/external_rules
#following works
#bspc config external_rules_command "$(which ~/.config/bspwm/external_rules)"

if [[ "$(hostname)" == "biskmatar" ]]; then
    bspc rule -a Steam desktop='^4' follow=off focus=on
    bspc rule -a jetbrains-studio desktop='^3' follow=off focus=on
    bspc rule -a Standard\ Notes desktop='^2' follow=off focus=on
    bspc rule -a burp-StartBurp desktop='^3' follow=off focus=on
fi

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# autostart some apps 
firefox &
alacritty -e tmux &
dunstify "Kernel.org" "$(~/bin/get_latest_kernel_version.sh)" &
